### PR TITLE
Add Skyline links

### PR DESCRIPTION
**Pull request by chambm**

### CODE REVIEW

**Comment by brendanx67** [comment]
Looks good. Thanks!

**Comment by bspratt** [comment]
Looks good, though the Skyline download at
http://proteowizard.sourceforge.net/download.html doesn't seem to work.

**Comment by chambm** [comment]
Indeed, and I can't figure out why. The js file on the sourceforge project web is updated, but what gets downloaded from the server is the old one without my changes. But the html files got updated and download as expected.

**Comment by chambm** [comment]
That's what it is supposed to do. Look at the code. The js file is being
aggressively cached somewhere on a proxy. I'll check Monday whether it's
fixed. You can try with your phone and see the file is updated on the
server.

>

**Comment by brendanx67** [comment]
Seemed to work on my phone and from home.

**Comment by chambm** [comment]
OK seems to be working fine now.

**Comment by bspratt** [comment]
Confirmed working here as well. Thanks!

Brian

**Pull request merged**
